const ActionType = {
    LOGIN: 'AUTH/LOGIN',
    LOGIN_SUCCESS: 'AUTH/LOGIN_SUCCESS',
    LOGIN_ERROR: 'AUTH/LOGIN_ERROR',
    LOGIN_RESET: 'AUTH/LOGIN_RESET',
    REGISTER: 'AUTH/REGISTER',
    REGISTER_SUCCESS: 'AUTH/REGISTER_SUCCESS',
    REGISTER_ERROR: 'AUTH/REGISTER_ERROR',
    REGISTER_RESET: 'AUTH/REGISTER_RESET'
};
export default ActionType;
